<?php

namespace app\controllers;

use app\models\ContactForm;
use app\models\Currency;
use app\models\District;
use app\models\DocType;
use app\models\LoginForm;
use app\models\Menu;
use app\models\Picture;
use app\models\Product;
use app\models\ProductSearch;
use app\models\ProductType;
use app\models\Province;
use app\models\Unit;
use app\models\User;
use GuzzleHttp\Psr7\Uri;
use Yii;
use yii\db\Exception;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\UploadedFile;

class SiteController extends Controller
{

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
                'view' => 'error'
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
//                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'onAuthSuccess'],
            ],
        ];
    }

    public function beforeAction($action)
    {
        $lang = Yii::$app->session->get("lang");
        if(!isset($lang)) $lang = Yii::$app->session->set("lang", "la-LA");
        if(Yii::$app->language != $lang )
            Yii::$app->language = $lang;

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function onAuthSuccess($client)
    {
        try {
            $userAttributes = $client->getUserAttributes();
            $user = User::find()
                ->where(isset($userAttributes['email'])? ["email" => $userAttributes['email']] :["facebookid" => $userAttributes['id']] )
                ->one();
            if(!isset($user)) {
                $user = new User();
                $user->registerd_date = date("Y-m-d H:i:s");
                $user->password = $userAttributes["id"];
                $user->facebookid = $userAttributes["id"];
                $user->email = isset($userAttributes["email"])? $userAttributes["email"]:$userAttributes["id"];
                $user->status = "A";
                $user->role = "U";
                $user->birthdate = date('Y-m-d H:i:s');
            }
            $user->facebookname = $userAttributes["name"];
            $user->firstname = $userAttributes["first_name"];
            $user->lastname = $userAttributes["last_name"];
            if(!$user->save()) {
                throw new Exception(json_encode($user->errors));
            } else {
                $user = User::findIdentity($user->email);
            }
            $user->password = "";
            Yii::$app->user->login($user, 60 * 60 * 24 * 30); //30 days
            Yii::$app->session->set("username", $userAttributes["name"]);
            Yii::$app->session->set("user", $user);
            return $this->redirect(["site/home"]);
        } catch (Exception $ex) {
            Yii::$app->session->setFlash('danger', $ex->getMessage());
            return $this->redirect(["site/index"]);
        }
    }

    public function actionHome()
    {
        if(!isset(Yii::$app->user->identity) && isset(Yii::$app->session['user'])) {
            Yii::$app->user->login(Yii::$app->session['user']);
        } else {
            Yii::$app->user->logout();
            return $this->redirect(['site/index']);
        }
        $this->layout = "home";
        return $this->render("home");
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $user = Yii::$app->session->get('user');
        if(isset($user)) {
            return $this->redirect(["site/home"]);
        }

        $models = Product::find()->where(["status" => "A"])->orderBy("created_date desc")->all();
        $this->layout = "index";
        return $this->render('index', [
            "models" => $models
        ]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest)
            return $this->goHome();

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post())) {
            if($model->login()) {
                return $this->goBack();
//            return $this->redirect(["home"]);
            }
        }
        $this->layout = "index";
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->session->set("user", null);
        Yii::$app->session->destroySession("user");
        Yii::$app->user->logout();
        return $this->redirect(["site/index"]);
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        $this->layout = "index";
        return $this->render('about');
    }

    public function actionView($id) {
        $model = $this->findProduct($id);
        if($model->status != "A") {
            Yii::$app->session->setFlash('warning', Yii::t('app', 'Not Found'));
            return $this->redirect(["site/index"]);
        }
        $this->layout = "index";
        $this->view->params['fbphoto'] = $model->photo;
        $this->view->params['fburl'] = "http://www.dinlao.com/web/index.php?r=site/view&id=".$model->id;
        $this->view->params['fbtitle'] = (Yii::$app->language == "la-LA"?$model->productType->namelao:$model->productType->name)." - ". $model->village;
        return $this->render("view", [
            'model' => $model
        ]);
    }

    public function actionGetdistricts($province) {
        $models = District::find()->where(["province_id" => $province])->orderBy(["id" => "asc"])->asArray()->all();
        echo json_encode($models);
    }

    protected function findProduct($id)
    {
        if (($model = Product::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionChangelang() {
        Yii::$app->language = Yii::$app->language == "en-US" ? "la-LA":"en-US";
        Yii::$app->session->set("lang", Yii::$app->language);

        return $this->goBack();
    }

    public function actionViewall() {
        $searchModel = new ProductSearch();
        $searchModel->status = "A";
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $this->layout = "index";
        return $this->render('viewall', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'provinces' => Province::find()->all(),
            'docTypes' => DocType::find()->all(),
            'currencies' => Currency::find()->all(),
            'units' => Unit::find()->all()
        ]);
    }

    public function actionRegister() {
        $this->layout = "index";
        $model = new User();
        if($model->load(Yii::$app->request->post())) {
            $post = Yii::$app->request->post();
            $model->confirmpassword = $post["User"]["confirmpassword"];

            if($model->confirmpassword != $model->password) {
                $model->addError("confirmpassword", Yii::t('app', 'Confirm Password is not matched'));
                return $this->render("register", ['model' => $model]);
            }

            $model->registerd_date = date("Y-m-d H:i:s");
            $model->birthdate = date('Y-m-d');
            $model->role = "U";
            $model->status = "A";
            if(!$model->save()) {
                return $this->render("register", ['model' => $model]);
            }

            Yii::$app->user->login($model, 60*60*24*10); //7 days
            Yii::$app->session->set("user", $model);

            return $this->redirect(["site/home"]);
        }

        return $this->render("register", [
            "model" => $model
        ]);
    }

    public function actionGetproducts() {
        $lang = Yii::$app->language == "la-LA"?"lao":"";
        $models = Product::find()
            ->select("product.id, price, currency.code currencycode, height, width, unit.code as unitcode, 
            village, district.name$lang districtname, province.name$lang provincename, 
            lat, lon, product_type.name$lang typename, product_type.code typecode")
            ->where(["status" => "A"])
            ->join("join", "currency", "currency_id=currency.id")
            ->join("join", "unit", "unit_id=unit.id")
            ->join("join", "district", "district_id=district.id")
            ->join("join", "province", "district.province_id=province.id")
            ->join("join", "product_type", "product_type_id=product_type.id")
            ->asArray()->all();

        echo json_encode($models);
    }
}
